AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deploy Amazon Linux 2 EC2 instance with Docker, Docker Compose, fixed private IP, 
  initialize Docker Swarm, token wordt weggeschreven naar EFS

Parameters:
  GCPProjectID:
    Type: String
    Description: GCP Project ID for Artifact Registry
  GCPRegion:
    Type: String
    Default: europe-west4
    Description: Region for Artifact Registry
  GCPRepo:
    Type: String
    Default: cloudshirt-docker
    Description: GCP Artifact Registry repository
  GCPServiceAccountJson:
    Type: String
    Description: Base64-encoded GCP service account key  
  InstanceType:
    Type: String
    Default: t3.small
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: vockey
  FixedPrivateIP:
    Type: String
    Description: Fixed private IP voor de manager EC2 (bijv. 10.0.1.10)
    Default: 10.0.1.10

Resources:
  WebInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0254b2d5c4c472488
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !ImportValue base-stack:CloudShirtFirstSubnet
      PrivateIpAddress: !Ref FixedPrivateIP
      SecurityGroupIds:
        - !ImportValue base-stack:InstanceSG
        - !ImportValue efs-stack:EFSSG
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: true 
      Tags:
        - Key: Name
          Value: CloudShirt-Web-1-DockerSwarmHost
      UserData:
        Fn::Base64: !Sub 
        - |
          #!/bin/bash -xe

          yum update -y
          yum install -y gcc git unzip curl jq nfs-utils amazon-efs-utils
          
          # Voeg Google Cloud SDK repo toe
          tee /etc/yum.repos.d/google-cloud-sdk.repo << EOL
          [google-cloud-sdk]
          name=Google Cloud SDK
          baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
          enabled=1
          gpgcheck=1
          repo_gpgcheck=0
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
                https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          EOL

           yum install -y docker google-cloud-sdk

          # Docker service starten
          systemctl enable docker
          systemctl start docker
          sleep 5

          # Docker Compose installeren
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          /usr/local/bin/docker-compose version
          usermod -aG docker ec2-user

          # EFS mounten
          mkdir -p /mnt/efs
          mount -t efs -o tls ${EFS_DNS}:/ /mnt/efs
          echo "${EFS_DNS}:/ /mnt/efs efs defaults,_netdev 0 0" >> /etc/fstab

          # Docker Swarm init
          docker swarm init

          # Maak join command en sla op op EFS
          TOKEN=$(docker swarm join-token worker -q)
          echo "docker swarm join --token $TOKEN 10.0.1.10:2377" > /mnt/efs/swarm-join-command.txt

          echo "${RDSENDPOINT}" > /mnt/efs/rds-endpoint

          # GCP service account login
          echo "${GCPServiceAccountJson}" | base64 --decode > /root/gcp-service-account.json
          gcloud auth activate-service-account --key-file=/root/gcp-service-account.json
          gcloud config set project ${GCPProjectID}
          gcloud auth configure-docker ${GCPRegion}-docker.pkg.dev --quiet


          cd "/home/ec2-user"
          echo "Current directory: $(pwd)"

          git clone https://github.com/537845Ahmed/CloudShirt-1.git

          cd "/home/ec2-user/CloudShirt-1"
          echo "Current directory: $(pwd)"
          
          # BASH SCRIPT VOOR ENDPOINT
          chmod +x endpointshetter-2.sh 
          ./endpointshetter-2.sh 

          # Build en push Docker images naar Google Artifact Registry
          cd "/home/ec2-user/CloudShirt-1"

          docker build -t ${GCPRegion}-docker.pkg.dev/${GCPProjectID}/${GCPRepo}/eshopwebmvc:latest -f src/Web/Dockerfile .
          docker push ${GCPRegion}-docker.pkg.dev/${GCPProjectID}/${GCPRepo}/eshopwebmvc:latest

          docker build -t ${GCPRegion}-docker.pkg.dev/${GCPProjectID}/${GCPRepo}/eshoppublicapi:latest -f src/PublicApi/Dockerfile .
          docker push ${GCPRegion}-docker.pkg.dev/${GCPProjectID}/${GCPRepo}/eshoppublicapi:latest
          
        - EFS_DNS: !ImportValue efs-stack:EFSDNS
          RDSENDPOINT: !ImportValue rds-stack:RDSEndpointAddress

Outputs:
  Instance1Id:
    Description: EC2 Instance 1 ID
    Value: !Ref WebInstance1
    Export:
      Name: !Sub "${AWS::StackName}:Instance1"

  SwarmJoinCommandEFS:
    Description: "Path to join command on EFS"
    Value: /mnt/efs/swarm-join-command.txt
    Export:
      Name: !Sub "${AWS::StackName}:SwarmJoinCommandEFS"
      
