AWSTemplateFormatVersion: 2010-09-09
Description: >
  Deploy Amazon RDS SQL Server instance and two Amazon Linux 2 EC2 instances with .NET 6, 
  nginx reverse proxy, and CloudShirt web app configured to use the RDS database.

Parameters:
  DBAllocatedStorage:
    Type: Number
    Default: 30
    Description: The size of the database (Gb)

Resources:
  CloudShirtDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: CloudShirt RDS subnet group
      SubnetIds:
        - !ImportValue base-stack:CloudShirtFirstPrivateSubnet
        - !ImportValue base-stack:CloudShirtSecondPrivateSubnet
      Tags:
        - Key: Name
          Value: CloudShirt-DBSubnetGroup

  CloudShirtDBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: Credentials for CloudShirt RDS master user
      GenerateSecretString:
        SecretStringTemplate: '{"username":"csadmin"}'
        GenerateStringKey: password
        PasswordLength: 20
        ExcludeCharacters: '"@/\\'

  CloudShirtRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: cloudshirt-db
      Engine: sqlserver-ex
      DBInstanceClass: db.t3.medium
      AllocatedStorage: !Ref DBAllocatedStorage
      MasterUsername: !Sub "{{resolve:secretsmanager:${CloudShirtDBSecret}:SecretString:username}}"
      MasterUserPassword: !Sub "{{resolve:secretsmanager:${CloudShirtDBSecret}:SecretString:password}}"
      LicenseModel: license-included
      MonitoringInterval: 0
      VPCSecurityGroups:
        - !ImportValue base-stack:rdsSG
      DBSubnetGroupName: !Ref CloudShirtDBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 1
      MultiAZ: false
      StorageType: gp2
      DeletionProtection: false
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

Outputs:
  RDSEndpointAddress:
    Description: The RDS endpoint address
    Value: !GetAtt CloudShirtRDSInstance.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}:RDSEndpointAddress"

  RDSSecretArn:
    Description: ARN for the generated RDS credentials secret
    Value: !Ref CloudShirtDBSecret
    Export:
      Name: !Sub "${AWS::StackName}:RDSSecretArn"
