Description: >
  CloudShirt Application Load Balancer Stack
  - Load Balancer (LB)
  - Target group voor EC2-instances
  - Listener op HTTP (poort 80)
  - Exporteert DNS-naam als output

Resources:
  # EC2-instances
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue cloudshirt-network:VPC
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckPath: /
      Targets:
        - Id: !ImportValue cloudshirt-ec2:Instance1
        - Id: !ImportValue cloudshirt-ec2:Instance2

  # Loadbalancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: cloudshirt-alb
      Subnets:
        - !ImportValue cloudshirt-network:CloudShirtFirstSubnet
        - !ImportValue cloudshirt-network:CloudShirtSecondSubnet
      SecurityGroups:
        - !ImportValue cloudshirt-network:InstanceSG
      Scheme: internet-facing
      Type: application

  # Listener voor HTTP
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref WebTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

# Output
Outputs:
  LoadBalancerDNSName:
    Description: Public URL for CloudShirt
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub "${AWS::StackName}:LoadBalancerDNS"

  WebTargetGroup:
    Description: ARN of the Target Group for port 5098
    Value: !Ref WebTargetGroup
    Export:
      Name: !Sub "${AWS::StackName}:WebTargetGroup"
